### ISSUE TITLE
Generare Features mancanti

### ISSUE THREAD

**Issue by Francescabazzo** [Francescabazzo/qpid#8]
Generare le seguenti features (non presenti nel dataset iniziale): 
- genere del partner che l'utente sta cercando (tre possibili valori: male, female, all); 
- età richiesta del partner ("età fissa") ed eventuale range di età; 
- luogo, espresso in longitudine e latitudine.

**Comment by evafumo** [comment]
Il genere del partner cercato è stato stimato tramite le percentuali Ipsos.
In primo luogo si è provveduto a creare una variabike di tipo testuale con tre possibili generi (he,him - she,her - they,them)
La codifica del genere cercatto è stata fatta introducendo 3 colonne nel dataset con flag 1= positiva ,0 = negativa:
-gender_partner_him: se il partner cercato è un uomo
-gender_partner_her se il partner cercato è una donna
-gender_partner_them: se il partner cercato è non-binary
è presente anche un colonna di riepilogo gender_partner dove il genere del partner cercato è rappresenatto in modo posizionale con valori 1,0. Prima posizione he,him, seconda posizione, she,her, terza posizione they,them.

L'età fissa è gia presente nel dataset, è stato generato un  raggio di ricerca compreso tra [0,100] ed è stata introdotta la colonna 
age_flag con valori 1,0 che simula la scelta dell'utente di impostare o meno un interallo d'età. Se la flag è 0, l'utente vuole usare l'età puntuale quindi il valore di age-range sarà 0, se è 1 lo user stabilsce un range.

Le features di longitudine e latitudine sono state generate con chatgpt
